[package]
name = "aqua_gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.35"
vulkano-shaders = "0.35"
vulkano-util = "0.35"

winit = {version = "0.30"}
egui_winit_vulkano = "0.28"

cgmath = "0.18"
serde = {version = "1.0", features = ["derive"]}