#version 450

layout(local_size_x = 256) in;

layout(push_constant) uniform Constants
{
    vec4 gravity;
    uint particle_count;
    float dt;
    
}
constants;

layout(set = 0, binding = 0) buffer VelocityBuffer
{
    vec4 velocities[];
};

void main()
{
    uint particle_id = gl_GlobalInvocationID.x;
    if (particle_id >= constants.particle_count)
        return;

    velocities[particle_id] += constants.gravity * constants.dt;
}